#!/usr/bin/python3 -I
"""User-level helper for xuanping.trackpad. Refuse to run as root."""

import fcntl
import json
import math
import os
import pwd
import re
import secrets
import select
import signal
import stat
import subprocess
import sys
import time

PLUGIN_ID = "xuanping.trackpad"
KEYS = ("drag3fg", "swipe4", "macosAccel")
LABELS = {
    "drag3fg": "Three-finger drag",
    "swipe4": "Four-finger swipe",
    "macosAccel": "macOS pointer curve",
}
FALLBACK_DEVICES = (
    "apple-inc.-magic-trackpad",
    "apple-inc.-magic-trackpad-1",
    "apple-inc.-magic-trackpad-2",
)
MACOS_ACCEL = (
    "custom 0.5 0.0 0.05 0.11 0.195 0.32 0.494 0.735 1.06 1.488 2.05 "
    "2.775 3.69 4.83 6.235 7.95 9.994 12.4 15.2 17.1 18.05 19.0 19.95"
)
MARKER_BEGIN = "-- BEGIN xuanping.trackpad"
MARKER_END = "-- END xuanping.trackpad"
REQUIRE_LINE = 'pcall(require, "hypr.xuanping-trackpad")'
PACK_HEADER = "-- Generated by xuanping.trackpad. Additive overlays only; do not edit.\n"
SAFE_DEVICE_NAME = re.compile(r"^[a-z0-9][a-z0-9._-]{0,62}$")
SAFE_COMPONENT = re.compile(r"^[A-Za-z0-9._-]+$")
HIDRAW_NODE = re.compile(r"^/dev/hidraw[0-9]{1,3}$")
SCROLL_TEXT = re.compile(r"^[0-9]{1,2}(\.[0-9]{1,2})?$")
SCROLL_MIN = 0.1
SCROLL_MAX = 2.0
SCROLL_DEFAULT = 0.3
UDEV_DEST = "/etc/udev/rules.d/70-xuanping-trackpad-hidraw.rules"
MAX_STATE = 4096
MAX_HYPR = 1048576
MAX_CMD = 65536
MAX_DEVICES = 64
MAX_HIDRAW = 32
MAX_POWER = 64
MAX_NAME = 96

APPLE_TRACKPAD_VP = frozenset({
    (0x05AC, 0x0265), (0x05AC, 0x0324), (0x05AC, 0x030E),
    (0x004C, 0x0265), (0x004C, 0x0324), (0x004C, 0x030E),
})

IOC_READ, IOC_WRITE = 2, 1
IOC_NRSHIFT, IOC_TYPESHIFT, IOC_SIZESHIFT, IOC_DIRSHIFT = 0, 8, 16, 30


def die(msg, code=1):
    print(msg, file=sys.stderr)
    raise SystemExit(code)


def home_dir():
    return pwd.getpwuid(os.geteuid()).pw_dir


def _ok_component(name):
    return bool(SAFE_COMPONENT.fullmatch(name)) and name not in (".", "..")


def open_dir_chain(parts, leaf_private=True, create=True):
    if not parts or not all(_ok_component(p) for p in parts):
        raise PermissionError("refusing directory chain")
    fd = os.open(home_dir(), os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
    try:
        for i, name in enumerate(parts):
            last = i == len(parts) - 1
            try:
                nfd = os.open(
                    name,
                    os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC,
                    dir_fd=fd,
                )
            except FileNotFoundError:
                if not create:
                    raise
                mode = 0o700 if (last and leaf_private) else 0o755
                try:
                    os.mkdir(name, mode, dir_fd=fd)
                except FileExistsError:
                    pass
                nfd = os.open(
                    name,
                    os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC,
                    dir_fd=fd,
                )
            os.close(fd)
            fd = nfd
            st = os.fstat(fd)
            if not stat.S_ISDIR(st.st_mode) or st.st_uid != os.geteuid():
                raise PermissionError(f"untrusted directory component {name}")
            if last and leaf_private and st.st_mode & 0o077:
                os.fchmod(fd, 0o700)
        return fd
    except BaseException:
        os.close(fd)
        raise


def read_bounded(dirfd, name, max_bytes, require_private=True):
    try:
        fd = os.open(
            name,
            os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK | os.O_CLOEXEC,
            dir_fd=dirfd,
        )
    except FileNotFoundError:
        return None
    try:
        st = os.fstat(fd)
        if (
            not stat.S_ISREG(st.st_mode)
            or st.st_uid != os.geteuid()
            or st.st_nlink != 1
            or st.st_size > max_bytes
        ):
            raise PermissionError("refusing state file")
        if require_private and st.st_mode & 0o077:
            os.fchmod(fd, 0o600)
        elif (not require_private) and st.st_mode & 0o002:
            raise PermissionError("refusing world-writable file")
        os.set_blocking(fd, True)
        data = b""
        while len(data) <= max_bytes:
            chunk = os.read(fd, min(65536, max_bytes + 1 - len(data)))
            if not chunk:
                break
            data += chunk
        if len(data) > max_bytes:
            raise PermissionError("state file grew past the limit")
        return data
    finally:
        os.close(fd)


def write_atomic(dirfd, name, data, mode=0o600):
    if len(data) > MAX_HYPR:
        raise ValueError("payload too large")
    tmp = f".{name}.{secrets.token_hex(8)}.tmp"
    fd = os.open(
        tmp,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC,
        mode,
        dir_fd=dirfd,
    )
    try:
        os.fchmod(fd, mode)
        view = memoryview(data)
        while view:
            n = os.write(fd, view)
            view = view[n:]
        os.fsync(fd)
        os.rename(tmp, name, src_dir_fd=dirfd, dst_dir_fd=dirfd)
        os.fsync(dirfd)
    except BaseException:
        try:
            os.unlink(tmp, dir_fd=dirfd)
        except OSError:
            pass
        raise
    finally:
        os.close(fd)


def unlink_named(dirfd, name):
    try:
        st = os.lstat(name, dir_fd=dirfd)
    except FileNotFoundError:
        return False
    if not stat.S_ISREG(st.st_mode) or st.st_uid != os.geteuid():
        raise PermissionError(f"refusing to delete {name}")
    os.unlink(name, dir_fd=dirfd)
    return True


def repair_state_dir(dirfd):
    try:
        names = os.listdir(f"/proc/self/fd/{dirfd}")
    except OSError:
        return
    for name in names:
        if not _ok_component(name):
            continue
        try:
            st = os.lstat(name, dir_fd=dirfd)
        except OSError:
            continue
        if stat.S_ISREG(st.st_mode):
            if st.st_uid == os.geteuid() and st.st_mode & 0o077:
                try:
                    fd = os.open(name, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=dirfd)
                    try:
                        os.fchmod(fd, 0o600)
                    finally:
                        os.close(fd)
                except OSError:
                    pass
            continue
        if stat.S_ISDIR(st.st_mode):
            continue
        try:
            os.unlink(name, dir_fd=dirfd)
        except OSError:
            pass


def state_dirfd():
    fd = open_dir_chain([".local", "state", "omarchy", PLUGIN_ID], leaf_private=True)
    repair_state_dir(fd)
    return fd


def hypr_dirfd(create=True):
    return open_dir_chain([".config", "hypr"], leaf_private=False, create=create)


def _child_env():
    keep = (
        "HOME",
        "USER",
        "LOGNAME",
        "XDG_RUNTIME_DIR",
        "XDG_CONFIG_HOME",
        "XDG_STATE_HOME",
        "WAYLAND_DISPLAY",
        "HYPRLAND_INSTANCE_SIGNATURE",
        "DBUS_SESSION_BUS_ADDRESS",
    )
    env = {k: os.environ[k] for k in keep if os.environ.get(k)}
    env["PATH"] = "/usr/bin:/bin"
    env["LC_ALL"] = "C.UTF-8"
    return env


def _kill_group(proc, sig):
    try:
        os.killpg(proc.pid, sig)
    except (ProcessLookupError, PermissionError, OSError):
        pass


def bounded_cmd(argv, max_bytes=MAX_CMD, timeout=2):
    if not argv or not os.path.isabs(argv[0]):
        raise ValueError("absolute executable required")
    proc = subprocess.Popen(
        argv,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
        env=_child_env(),
    )
    deadline = time.monotonic() + timeout
    out = bytearray()
    fd = proc.stdout.fileno()
    try:
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise subprocess.TimeoutExpired(argv, timeout)
            ready, _, _ = select.select([proc.stdout], [], [], remaining)
            if not ready:
                raise subprocess.TimeoutExpired(argv, timeout)
            chunk = os.read(fd, min(65536, max_bytes + 1 - len(out)))
            if not chunk:
                break
            out += chunk
            if len(out) > max_bytes:
                _kill_group(proc, signal.SIGTERM)
                try:
                    proc.wait(timeout=2)
                except subprocess.TimeoutExpired:
                    _kill_group(proc, signal.SIGKILL)
                    proc.wait(timeout=1)
                raise ValueError("command output too large")
        rc = proc.wait(timeout=max(0.1, deadline - time.monotonic()))
    except subprocess.TimeoutExpired:
        _kill_group(proc, signal.SIGTERM)
        try:
            proc.wait(timeout=2)
        except subprocess.TimeoutExpired:
            _kill_group(proc, signal.SIGKILL)
            proc.wait(timeout=1)
        raise
    if rc != 0:
        raise subprocess.CalledProcessError(rc, argv)
    return bytes(out)


def show_osd(msg):
    if not msg:
        return
    try:
        bounded_cmd(["/usr/bin/omarchy-osd", "-i", "touchpad", "-m", msg], max_bytes=256, timeout=2)
    except (OSError, ValueError, subprocess.SubprocessError):
        pass


def ioc(direction, type_, nr, size):
    return (
        (direction << IOC_DIRSHIFT)
        | (ord(type_) << IOC_TYPESHIFT)
        | (nr << IOC_NRSHIFT)
        | (size << IOC_SIZESHIFT)
    )


def clip_text(value, n=MAX_NAME):
    out = []
    for ch in str(value or ""):
        code = ord(ch)
        if ch in "<>&" or code < 32 or 0x7F <= code <= 0x9F:
            continue
        if ch.isprintable() or ch == " ":
            out.append(ch)
        if len(out) >= n:
            break
    return "".join(out)


def default_state():
    out = {key: True for key in KEYS}
    out["scrollFactor"] = SCROLL_DEFAULT
    return out


def coerce_scroll_factor(value):
    if isinstance(value, bool) or value is None:
        return None
    if isinstance(value, int):
        n = float(value)
    elif isinstance(value, float):
        n = value
    else:
        text = str(value).strip()
        if len(text) > 8 or not SCROLL_TEXT.fullmatch(text):
            return None
        n = float(text)
    if not math.isfinite(n):
        return None
    n = round(n, 2)
    if n < SCROLL_MIN or n > SCROLL_MAX:
        return None
    return n


def parse_scroll_factor(value):
    n = coerce_scroll_factor(value)
    if n is None:
        die("scroll factor must be 0.10..2.00")
    return n


def load_json_file(dirfd, name, max_bytes=MAX_STATE):
    raw = read_bounded(dirfd, name, max_bytes)
    if raw is None:
        return None
    try:
        data, _ = json.JSONDecoder().raw_decode(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError):
        return None
    return data if isinstance(data, dict) else None


def load_state(dirfd):
    data = load_json_file(dirfd, "features.json")
    if data is not None:
        out = default_state()
        for key in KEYS:
            if key in data:
                out[key] = data[key] is True
        factor = coerce_scroll_factor(data.get("scrollFactor"))
        if factor is not None:
            out["scrollFactor"] = factor
        return out
    raw = read_bounded(dirfd, "enabled", MAX_STATE)
    if raw is not None:
        value = raw.decode("utf-8", "replace").strip() != "0"
        out = {key: value for key in KEYS}
        out["scrollFactor"] = SCROLL_DEFAULT
        return out
    return default_state()


def save_state(dirfd, state):
    payload = {key: bool(state[key]) for key in KEYS}
    payload["scrollFactor"] = parse_scroll_factor(state.get("scrollFactor", SCROLL_DEFAULT))
    write_atomic(dirfd, "features.json", (json.dumps(payload, indent=2) + "\n").encode())
    return payload


def load_notify(dirfd):
    data = load_json_file(dirfd, "notify.json") or {}
    n = data.get("lastNotifiedPercent", 100)
    if not isinstance(n, int) or n < 0 or n > 100:
        n = 100
    return {"lastNotifiedPercent": n}


def save_notify(dirfd, percent):
    if not isinstance(percent, int) or percent < 0 or percent > 100:
        die("notify percent must be 0..100")
    payload = {"lastNotifiedPercent": percent}
    write_atomic(dirfd, "notify.json", (json.dumps(payload) + "\n").encode())
    return payload


def lua_quote(name):
    escaped = (
        name.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def hypr_internal_name(name):
    return "".join("-" if ch in " \n," else ch.lower() for ch in str(name))


def classify_trackpad_name(name):
    if "magic-trackpad" in name or "magictrackpad" in name:
        return 2
    if "trackpad" in name or "touchpad" in name:
        return 1
    return 0


def hypr_devices_json():
    try:
        raw = bounded_cmd(["/usr/bin/hyprctl", "devices", "-j"], max_bytes=MAX_CMD, timeout=2)
        data = json.loads(raw.decode("utf-8"))
    except (OSError, ValueError, subprocess.SubprocessError, json.JSONDecodeError, UnicodeDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def discover_devices():
    names = set(FALLBACK_DEVICES)
    data = hypr_devices_json()
    for group in ("mice", "touchpads"):
        items = data.get(group) or []
        if not isinstance(items, list):
            continue
        for dev in items[:MAX_DEVICES]:
            if not isinstance(dev, dict):
                continue
            name = hypr_internal_name(dev.get("name") or "")
            if SAFE_DEVICE_NAME.fullmatch(name) and classify_trackpad_name(name) >= 2:
                names.add(name)
    return sorted(name for name in names if SAFE_DEVICE_NAME.fullmatch(name))[:MAX_DEVICES]


def render_lua(state):
    header = PACK_HEADER + "-- Disabled switches omit their keys instead of writing 0/false.\n"
    if not any(state[key] for key in KEYS):
        return header + "return\n"
    devices = discover_devices()
    quoted = ", ".join(lua_quote(name) for name in devices)
    parts = [header]
    if state["macosAccel"]:
        parts.append(f'local macos_accel =\n  "{MACOS_ACCEL}"\n\n')
    fields = []
    if state["macosAccel"]:
        fields.append("    sensitivity = 0,")
        fields.append("    accel_profile = macos_accel,")
    if state["drag3fg"]:
        fields.append("    drag_3fg = 1,")
        fields.append("    tap_and_drag = false,")
    fields.append("    natural_scroll = true,")
    factor = coerce_scroll_factor(state.get("scrollFactor")) or SCROLL_DEFAULT
    fields.append(f"    scroll_factor = {factor:.2f},")
    parts.append(
        "for _, name in ipairs({ %s }) do\n  hl.device({\n    name = name,\n%s\n  })\nend\n"
        % (quoted, "\n".join(fields))
    )
    if state["swipe4"]:
        parts.append(
            'hl.gesture({ fingers = 4, direction = "horizontal", action = "scroll_move" })\n'
        )
    return "".join(parts)


def applied_flags(text):
    return {
        "drag3fg": "drag_3fg = 1" in text,
        "swipe4": "scroll_move" in text,
        "macosAccel": "macos_accel" in text and "accel_profile = macos_accel" in text,
    }


def read_hypr_text(dirfd, name):
    raw = read_bounded(dirfd, name, MAX_HYPR, require_private=False)
    if raw is None:
        return None
    return raw.decode("utf-8")


def write_hypr_text(dirfd, name, text):
    write_atomic(dirfd, name, text.encode("utf-8"), mode=0o644)


def expected_require_block():
    return f"{MARKER_BEGIN}\n{REQUIRE_LINE}\n{MARKER_END}"


def validate_markers(text):
    if text.count(MARKER_BEGIN) != text.count(MARKER_END):
        return False
    if text.count(MARKER_BEGIN) > 1:
        return False
    if MARKER_BEGIN not in text:
        return True
    start = text.find(MARKER_BEGIN)
    end = text.find(MARKER_END)
    if start < 0 or end < start:
        return False
    block = text[start : end + len(MARKER_END)].strip()
    return block == expected_require_block()


def ensure_require(dirfd):
    text = read_hypr_text(dirfd, "hyprland.lua")
    if text is None:
        die("missing ~/.config/hypr/hyprland.lua")
    if not validate_markers(text):
        die("refusing malformed xuanping.trackpad markers in hyprland.lua")
    if MARKER_BEGIN in text:
        return False
    backup = read_bounded(dirfd, "hyprland.lua.xuanping-trackpad.bak", MAX_HYPR, require_private=False)
    if backup is None:
        write_hypr_text(dirfd, "hyprland.lua.xuanping-trackpad.bak", text)
    block = expected_require_block() + "\n"
    needle = 'require("hypr.input")'
    idx = text.find(needle)
    if idx >= 0:
        nl = text.find("\n", idx)
        insert_at = nl + 1 if nl >= 0 else len(text)
        text = text[:insert_at] + "\n" + block + "\n" + text[insert_at:]
    else:
        text = text.rstrip() + ("\n\n" if text.strip() else "") + block + "\n"
    write_hypr_text(dirfd, "hyprland.lua", text)
    return True


def remove_require(dirfd):
    text = read_hypr_text(dirfd, "hyprland.lua")
    if text is None:
        return False
    if not validate_markers(text):
        die("refusing malformed xuanping.trackpad markers in hyprland.lua")
    if MARKER_BEGIN not in text:
        return False
    start = text.find(MARKER_BEGIN)
    end = text.find(MARKER_END) + len(MARKER_END)
    while end < len(text) and text[end] == "\n":
        end += 1
        break
    if start > 0 and text[start - 1] == "\n":
        start -= 1
    text = text[:start] + text[end:]
    if not text.endswith("\n"):
        text += "\n"
    write_hypr_text(dirfd, "hyprland.lua", text)
    return True


def configerrors():
    try:
        raw = bounded_cmd(["/usr/bin/hyprctl", "configerrors"], max_bytes=65536, timeout=3)
        return raw.decode("utf-8", "replace").strip()
    except (OSError, ValueError, subprocess.SubprocessError):
        return ""


def reload_hypr():
    try:
        bounded_cmd(["/usr/bin/hyprctl", "reload"], max_bytes=4096, timeout=5)
        return True
    except (OSError, ValueError, subprocess.SubprocessError):
        return False


def apply_overlay(dirfd, state):
    desired = render_lua(state)
    current = read_hypr_text(dirfd, "xuanping-trackpad.lua")
    changed = current != desired
    if changed:
        before_err = configerrors()
        write_hypr_text(dirfd, "xuanping-trackpad.lua", desired)
        require_changed = ensure_require(dirfd)
        if reload_hypr():
            after_err = configerrors()
            if after_err and after_err != before_err:
                if current is not None:
                    write_hypr_text(dirfd, "xuanping-trackpad.lua", current)
                else:
                    unlink_named(dirfd, "xuanping-trackpad.lua")
                reload_hypr()
                die("hyprctl configerrors after overlay write; rolled back")
        return True, True
    require_changed = ensure_require(dirfd)
    if require_changed:
        reload_hypr()
        return True, True
    require_present = MARKER_BEGIN in (read_hypr_text(dirfd, "hyprland.lua") or "")
    return False, require_present


def status_payload(state, require_present, changed=False, osd=""):
    text = ""
    try:
        hypr = hypr_dirfd(create=False)
    except FileNotFoundError:
        hypr = None
    if hypr is not None:
        try:
            text = read_hypr_text(hypr, "xuanping-trackpad.lua") or ""
        finally:
            os.close(hypr)
    flags = applied_flags(text)
    return {
        "drag3fg": state["drag3fg"],
        "swipe4": state["swipe4"],
        "macosAccel": state["macosAccel"],
        "enabled": any(state[key] for key in KEYS),
        "applied": flags,
        "requirePresent": require_present,
        "scrollFactor": parse_scroll_factor(state.get("scrollFactor", SCROLL_DEFAULT)),
        "changed": bool(changed),
        "osd": osd,
    }


def parse_bool(value):
    text = str(value).strip().lower()
    if text in ("1", "on", "true", "yes"):
        return True
    if text in ("0", "off", "false", "no"):
        return False
    die(f"expected on/off, got {value!r}")


def parse_hid_id(hid_id):
    parts = (hid_id or "").strip().split(":")
    if len(parts) != 3:
        return None
    try:
        return tuple(int(part, 16) for part in parts)
    except ValueError:
        return None


def is_apple_trackpad_id(hid_id):
    parsed = parse_hid_id(hid_id)
    if not parsed:
        return False
    _bus, vendor, product = parsed
    return (vendor, product) in APPLE_TRACKPAD_VP


def text_has_trackpad(blob):
    lowered = (blob or "").lower()
    return "trackpad" in lowered or "touchpad" in lowered


def read_sysfs_file(path, max_bytes=4096):
    resolved = os.path.realpath(path)
    if not resolved.startswith("/sys/"):
        return None
    try:
        fd = os.open(resolved, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK | os.O_CLOEXEC)
    except OSError:
        return None
    try:
        st = os.fstat(fd)
        if not stat.S_ISREG(st.st_mode) or st.st_size > max_bytes:
            return None
        os.set_blocking(fd, True)
        data = os.read(fd, max_bytes + 1)
        if len(data) > max_bytes:
            return None
        return data.decode("utf-8", "replace")
    finally:
        os.close(fd)


def read_uevent(path):
    raw = read_sysfs_file(path)
    if raw is None:
        return None
    data = {}
    for line in raw.splitlines()[:64]:
        if "=" in line:
            key, value = line.split("=", 1)
            if len(key) <= 64:
                data[key] = value[:256]
    return data


def hid_info_from(path):
    cur = path
    seen = set()
    for _ in range(8):
        resolved = os.path.realpath(cur)
        if not resolved.startswith("/sys/") or resolved in seen:
            break
        seen.add(resolved)
        data = read_uevent(os.path.join(resolved, "uevent")) or {}
        if data.get("HID_ID") or data.get("HID_NAME"):
            return data
        nxt = os.path.join(resolved, "device")
        if os.path.exists(nxt):
            cur = nxt
            continue
        parent = os.path.dirname(resolved)
        if parent == resolved:
            break
        cur = parent
    return {}


def sysfs_battery():
    root = "/sys/class/power_supply"
    if not os.path.isdir(root):
        return None
    best, best_score = None, -1
    try:
        entries = sorted(os.listdir(root))[:MAX_POWER]
    except OSError:
        return None
    for name in entries:
        if not _ok_component(name):
            continue
        path = os.path.join(root, name)
        data = read_uevent(os.path.join(path, "uevent"))
        if not data or data.get("POWER_SUPPLY_TYPE") != "Battery":
            continue
        if data.get("POWER_SUPPLY_SCOPE") != "Device":
            continue
        model = clip_text(data.get("POWER_SUPPLY_MODEL_NAME", ""))
        ps_name = clip_text(data.get("POWER_SUPPLY_NAME", ""))
        hid = hid_info_from(path)
        hid_name = clip_text(hid.get("HID_NAME", ""))
        hid_id = hid.get("HID_ID", "")
        blob = f"{model} {ps_name} {hid_name}"
        if is_apple_trackpad_id(hid_id):
            score = 3
        elif text_has_trackpad(blob):
            score = 2
        else:
            continue
        try:
            capacity = int(data.get("POWER_SUPPLY_CAPACITY", "-1"))
        except ValueError:
            capacity = -1
        rec = {
            "present": data.get("POWER_SUPPLY_PRESENT", "1") == "1",
            "percentage": capacity,
            "status": clip_text(data.get("POWER_SUPPLY_STATUS", "Unknown"), 24),
            "model": model or hid_name or ps_name,
            "path": path[:128],
            "source": "sysfs",
            "stale": False,
        }
        if score > best_score:
            best, best_score = rec, score
    return best


def hidraw_devices():
    sysfs = "/sys/class/hidraw"
    if not os.path.isdir(sysfs):
        return []
    found = []
    try:
        entries = sorted(os.listdir(sysfs))[:MAX_HIDRAW]
    except OSError:
        return []
    for entry in entries:
        if not re.fullmatch(r"hidraw[0-9]{1,3}", entry):
            continue
        data = read_uevent(os.path.join(sysfs, entry, "device", "uevent")) or {}
        hid_id = data.get("HID_ID", "")
        if not is_apple_trackpad_id(hid_id):
            continue
        node = f"/dev/{entry}"
        if not HIDRAW_NODE.fullmatch(node):
            continue
        found.append((node, clip_text(data.get("HID_NAME", "") or "Magic Trackpad")))
    return found


def hypr_trackpad_present():
    data = hypr_devices_json()
    for group in ("mice", "touchpads"):
        items = data.get(group) or []
        if not isinstance(items, list):
            continue
        for dev in items[:MAX_DEVICES]:
            if not isinstance(dev, dict):
                continue
            name = str(dev.get("name") or "").lower()
            if "magic-trackpad" in name or "trackpad" in name:
                return True
    return False


def hidraw_battery():
    # Input report 0x90: [id, status_flags, capacity]. Bit 1 of status = charging.
    # HIDIOCGINPUT is _IOC_READ|_IOC_WRITE, so Linux requires O_RDWR; we never write(2).
    for dev, name in hidraw_devices():
        try:
            fd = os.open(dev, os.O_RDWR | os.O_NOFOLLOW | os.O_CLOEXEC)
        except OSError:
            continue
        try:
            st = os.fstat(fd)
            if not stat.S_ISCHR(st.st_mode):
                continue
            for size in (3, 4, 8):
                buf = bytearray(size)
                buf[0] = 0x90
                try:
                    fcntl.ioctl(fd, ioc(IOC_READ | IOC_WRITE, "H", 0x0A, size), buf)
                except OSError:
                    try:
                        fcntl.ioctl(fd, ioc(IOC_READ | IOC_WRITE, "H", 0x07, size), buf)
                    except OSError:
                        continue
                if buf[0] not in (0x90, 0) and size > 1:
                    continue
                capacity = buf[2] if size > 2 else -1
                if not (0 < capacity <= 100):
                    continue
                charging = bool(buf[1] & 0x02) if size > 1 else False
                return {
                    "present": True,
                    "percentage": int(capacity),
                    "status": "Charging" if charging else "Discharging",
                    "model": name,
                    "path": dev,
                    "source": "hidraw",
                    "stale": False,
                }
        finally:
            os.close(fd)
    return None


def load_cache(dirfd):
    data = load_json_file(dirfd, "battery-cache.json")
    if not data:
        return None
    pct = data.get("percentage")
    if not isinstance(pct, int) or pct <= 0 or pct > 100:
        return None
    saved = data.get("savedAt")
    if saved is not None and not isinstance(saved, (int, float)):
        return None
    return data


def save_cache(dirfd, rec, now):
    payload = {
        "percentage": rec["percentage"],
        "status": clip_text(rec.get("status", "Discharging"), 24),
        "model": clip_text(rec.get("model", "")),
        "savedAt": now,
    }
    write_atomic(dirfd, "battery-cache.json", (json.dumps(payload) + "\n").encode())


def battery_payload():
    now = time.time()
    dirfd = state_dirfd()
    try:
        cache = load_cache(dirfd)
        sys_rec = sysfs_battery()
        hid_rec = hidraw_battery() if (not sys_rec or sys_rec.get("percentage", -1) <= 0) else None
        connected = bool(sys_rec) or bool(hidraw_devices()) or hypr_trackpad_present()

        def cache_rec(model="", path=""):
            if not cache:
                return None
            return {
                "present": True,
                "percentage": cache["percentage"],
                "status": clip_text(cache.get("status", "Discharging"), 24),
                "model": clip_text(model or cache.get("model", "")),
                "path": path[:128],
                "source": "cache",
                "stale": True,
            }

        chosen = {
            "present": False,
            "percentage": -1,
            "status": "Disconnected",
            "model": "",
            "source": "none",
            "stale": False,
        }
        if hid_rec:
            chosen = hid_rec
        elif sys_rec and sys_rec.get("percentage", -1) > 0:
            chosen = sys_rec
        elif sys_rec and sys_rec.get("present"):
            chosen = cache_rec(sys_rec.get("model", ""), sys_rec.get("path", "")) or {
                "present": True,
                "percentage": -1,
                "status": clip_text(sys_rec.get("status", "Unknown"), 24),
                "model": clip_text(sys_rec.get("model", "")),
                "path": str(sys_rec.get("path", ""))[:128],
                "source": "sysfs",
                "stale": False,
            }
        elif connected:
            chosen = cache_rec() or {
                "present": True,
                "percentage": -1,
                "status": "Unknown",
                "model": clip_text((cache or {}).get("model", "")),
                "source": "hypr",
                "stale": False,
            }
        elif cache and (now - float(cache.get("savedAt", 0))) < 180:
            chosen = cache_rec()
        if chosen.get("present") and chosen.get("percentage", -1) > 0 and not chosen.get("stale"):
            save_cache(dirfd, chosen, now)
        chosen["model"] = clip_text(chosen.get("model", ""))
        chosen["status"] = clip_text(chosen.get("status", ""), 24)
        return chosen
    finally:
        os.close(dirfd)


def udev_rule_installed():
    try:
        fd = os.open(UDEV_DEST, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC)
    except OSError:
        return False
    try:
        st = os.fstat(fd)
        return stat.S_ISREG(st.st_mode) and not (st.st_mode & 0o002)
    finally:
        os.close(fd)


def hidraw_status():
    return {
        "ruleInstalled": udev_rule_installed(),
        "readable": hidraw_battery() is not None,
    }


def require_present(dirfd):
    text = read_hypr_text(dirfd, "hyprland.lua") or ""
    return MARKER_BEGIN in text


def cmd_mutate(cmd, argv):
    state_fd = state_dirfd()
    try:
        state = load_state(state_fd)
        osd = ""
        if cmd == "set":
            if len(argv) < 2:
                die("usage: trackpad-pack set <drag3fg|swipe4|macosAccel|scrollFactor> <value>")
            key, value = argv[0], argv[1]
            if key == "scrollFactor":
                state["scrollFactor"] = parse_scroll_factor(value)
                osd = f"Scroll speed {state['scrollFactor']:.2f}"
            elif key not in KEYS:
                die(f"unknown feature {key}")
            else:
                state[key] = parse_bool(value)
                osd = f"{LABELS[key]} {'on' if state[key] else 'off'}"
        elif cmd == "toggle":
            if not argv:
                die("usage: trackpad-pack toggle <drag3fg|swipe4|macosAccel>")
            key = argv[0]
            if key not in KEYS:
                die(f"unknown feature {key}")
            state[key] = not state[key]
            osd = f"{LABELS[key]} {'on' if state[key] else 'off'}"
        elif cmd == "enable":
            state = default_state()
            osd = "Trackpad feel on"
        elif cmd == "disable":
            factor = coerce_scroll_factor(state.get("scrollFactor")) or SCROLL_DEFAULT
            state = {key: False for key in KEYS}
            state["scrollFactor"] = factor
            osd = "Trackpad feel off"
        elif cmd != "apply":
            die(f"unknown command {cmd}")
        state = save_state(state_fd, state)
    finally:
        os.close(state_fd)

    hypr = hypr_dirfd()
    try:
        changed, present = apply_overlay(hypr, state)
        emit(status_payload(state, present, changed, osd))
        show_osd(osd)
    finally:
        os.close(hypr)


def cmd_status():
    state_fd = state_dirfd()
    try:
        state = load_state(state_fd)
    finally:
        os.close(state_fd)
    try:
        hypr = hypr_dirfd(create=False)
    except FileNotFoundError:
        emit(status_payload(state, False, False, ""))
        return
    try:
        present = require_present(hypr)
    finally:
        os.close(hypr)
    emit(status_payload(state, present, False, ""))


def cmd_uninstall():
    hypr = hypr_dirfd()
    try:
        removed_require = remove_require(hypr)
        pack = read_hypr_text(hypr, "xuanping-trackpad.lua")
        removed_pack = False
        if pack is not None and pack.startswith("-- Generated by xuanping.trackpad"):
            removed_pack = unlink_named(hypr, "xuanping-trackpad.lua")
        reload_hypr()
    finally:
        os.close(hypr)
    state_fd = state_dirfd()
    try:
        for name in ("features.json", "battery-cache.json", "notify.json", "enabled"):
            try:
                unlink_named(state_fd, name)
            except PermissionError:
                pass
    finally:
        os.close(state_fd)
    emit({"removedRequire": removed_require, "removedPack": removed_pack})


def emit(obj):
    sys.stdout.write(json.dumps(obj, separators=(",", ":")) + "\n")


def main(argv):
    if os.geteuid() == 0:
        die("refusing to run as root")
    cmd = argv[0] if argv else "status"
    if cmd in ("apply", "set", "toggle", "enable", "disable"):
        cmd_mutate(cmd, argv[1:])
    elif cmd == "status":
        cmd_status()
    elif cmd == "battery":
        emit(battery_payload())
    elif cmd == "notify-get":
        fd = state_dirfd()
        try:
            emit(load_notify(fd))
        finally:
            os.close(fd)
    elif cmd == "notify-set":
        if len(argv) < 2:
            die("usage: trackpad-pack notify-set <0-100>")
        try:
            percent = int(argv[1], 10)
        except ValueError:
            die("notify percent must be an integer")
        fd = state_dirfd()
        try:
            emit(save_notify(fd, percent))
        finally:
            os.close(fd)
    elif cmd == "hidraw-status":
        emit(hidraw_status())
    elif cmd == "uninstall":
        cmd_uninstall()
    else:
        die(f"unknown command {cmd}")


if __name__ == "__main__":
    main(sys.argv[1:])
